// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {proxy} from '../models';
import {sites} from '../models';

export function CheckServicesReady():Promise<boolean>;

export function GetAllServicesStatus():Promise<services.AllServicesStatus>;

export function GetProxyList():Promise<Array<proxy.ProxyInfo>>;

export function GetSitesList():Promise<Array<sites.SiteInfo>>;

export function StartServer():Promise<string>;

export function StopServer():Promise<string>;
