// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckServicesReady() {
  return window['go']['admin']['App']['CheckServicesReady']();
}

export function GetAllServicesStatus() {
  return window['go']['admin']['App']['GetAllServicesStatus']();
}

export function GetProxyList() {
  return window['go']['admin']['App']['GetProxyList']();
}

export function GetSitesList() {
  return window['go']['admin']['App']['GetSitesList']();
}

export function StartServer() {
  return window['go']['admin']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['admin']['App']['StopServer']();
}
