// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckServicesReady() {
  return window['go']['admin']['App']['CheckServicesReady']();
}

export function CreateNewSite(arg1) {
  return window['go']['admin']['App']['CreateNewSite'](arg1);
}

export function DeleteSite(arg1) {
  return window['go']['admin']['App']['DeleteSite'](arg1);
}

export function DisableProxyService() {
  return window['go']['admin']['App']['DisableProxyService']();
}

export function EnableProxyService() {
  return window['go']['admin']['App']['EnableProxyService']();
}

export function GetAllServicesStatus() {
  return window['go']['admin']['App']['GetAllServicesStatus']();
}

export function GetConfig() {
  return window['go']['admin']['App']['GetConfig']();
}

export function GetProxyList() {
  return window['go']['admin']['App']['GetProxyList']();
}

export function GetSitesList() {
  return window['go']['admin']['App']['GetSitesList']();
}

export function GetVAccessRules(arg1, arg2) {
  return window['go']['admin']['App']['GetVAccessRules'](arg1, arg2);
}

export function OpenSiteFolder(arg1) {
  return window['go']['admin']['App']['OpenSiteFolder'](arg1);
}

export function ReloadConfig() {
  return window['go']['admin']['App']['ReloadConfig']();
}

export function ReloadSSLCertificates() {
  return window['go']['admin']['App']['ReloadSSLCertificates']();
}

export function RestartAllServices() {
  return window['go']['admin']['App']['RestartAllServices']();
}

export function SaveConfig(arg1) {
  return window['go']['admin']['App']['SaveConfig'](arg1);
}

export function SaveVAccessRules(arg1, arg2, arg3) {
  return window['go']['admin']['App']['SaveVAccessRules'](arg1, arg2, arg3);
}

export function StartHTTPSService() {
  return window['go']['admin']['App']['StartHTTPSService']();
}

export function StartHTTPService() {
  return window['go']['admin']['App']['StartHTTPService']();
}

export function StartMySQLService() {
  return window['go']['admin']['App']['StartMySQLService']();
}

export function StartPHPService() {
  return window['go']['admin']['App']['StartPHPService']();
}

export function StartServer() {
  return window['go']['admin']['App']['StartServer']();
}

export function StopHTTPSService() {
  return window['go']['admin']['App']['StopHTTPSService']();
}

export function StopHTTPService() {
  return window['go']['admin']['App']['StopHTTPService']();
}

export function StopMySQLService() {
  return window['go']['admin']['App']['StopMySQLService']();
}

export function StopPHPService() {
  return window['go']['admin']['App']['StopPHPService']();
}

export function StopServer() {
  return window['go']['admin']['App']['StopServer']();
}

export function UpdateSiteCache() {
  return window['go']['admin']['App']['UpdateSiteCache']();
}

export function UploadCertificate(arg1, arg2, arg3) {
  return window['go']['admin']['App']['UploadCertificate'](arg1, arg2, arg3);
}
