// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {proxy} from '../models';
import {sites} from '../models';
import {vaccess} from '../models';

export function CheckServicesReady():Promise<boolean>;

export function DisableProxyService():Promise<string>;

export function EnableProxyService():Promise<string>;

export function GetAllServicesStatus():Promise<services.AllServicesStatus>;

export function GetConfig():Promise<any>;

export function GetProxyList():Promise<Array<proxy.ProxyInfo>>;

export function GetSitesList():Promise<Array<sites.SiteInfo>>;

export function GetVAccessRules(arg1:string,arg2:boolean):Promise<vaccess.VAccessConfig>;

export function OpenSiteFolder(arg1:string):Promise<string>;

export function ReloadConfig():Promise<string>;

export function RestartAllServices():Promise<string>;

export function SaveConfig(arg1:string):Promise<string>;

export function SaveVAccessRules(arg1:string,arg2:boolean,arg3:string):Promise<string>;

export function StartHTTPSService():Promise<string>;

export function StartHTTPService():Promise<string>;

export function StartMySQLService():Promise<string>;

export function StartPHPService():Promise<string>;

export function StartServer():Promise<string>;

export function StopHTTPSService():Promise<string>;

export function StopHTTPService():Promise<string>;

export function StopMySQLService():Promise<string>;

export function StopPHPService():Promise<string>;

export function StopServer():Promise<string>;

export function UpdateSiteCache():Promise<string>;
